title: CECAM tutorial 2025
author: Osamu Waseda

execute:
  execute_notebooks           : off

repository:
    url                       : https://github.com/pyiron-workshop/CECAM-2024
    path_to_book              : ""

launch_buttons:
  notebook_interface          : jupyterlab
  binderhub_url               : https://mybinder.org
