channels:
- conda-forge
dependencies:
- pyiron_workflow =0.12.1
- matplotlib =3.10.3
- pint =0.24.4
- semantikon =0.0.16
- atomistics =0.2.4
- lammps =2024.06.27=*_openmpi_*
- iprpy-data
- pyiron_workflow =0.12.1
- python =3.12
- pylammpsmpi =0.2.31
- jinja2 =3.1.6
- pyiron_lammps =0.4.0
